CREATE DATABASE REDSOCIAL;

USE REDSOCIAL;

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(30),
    CORREO_USUARIO VARCHAR(30),
    CONTRASENA_USUARIO VARCHAR(100),
    USUARIO_ADMIN BOOLEAN
);

CREATE TABLE AMISTAD (
    ID_USUARIO_1 INT,
    ID_USUARIO_2 INT,
    FOREIGN KEY (ID_USUARIO_1) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USUARIO_2) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE POST_USUARIO (
    ID_POST INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO_POST INT,
    FOREIGN KEY (ID_USUARIO_POST) REFERENCES USUARIO(ID_USUARIO)
);