CREATE DATABASE REDSOCIAL;

USE REDSOCIAL;

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(30),
    CORREO_USUARIO VARCHAR(30),
    CONTRASENA_USUARIO VARCHAR(100),
    USUARIO_ADMIN BOOLEAN
);

CREATE TABLE AMISTAD (
    ID_USUARIO_1 INT,
    ID_USUARIO_2 INT,
    FOREIGN KEY (ID_USUARIO_1) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USUARIO_2) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE POST_USUARIO (
    ID_POST INT AUTO_INCREMENT PRIMARY KEY, -- EL ID DEL POST
    ID_USUARIO_POST INT, -- HACE REFERENCIA AL ID DEL USUARIO QUE CREÓ EL POST
    FOREIGN KEY (ID_USUARIO_POST) REFERENCES USUARIO(ID_USUARIO),
    TEXTO_POST VARCHAR(300) -- EL TEXTO DEL POST
);

CREATE TABLE COMENTARIO (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY, -- EL ID DEL COMENTARIO
    ID_COMENTARIO_POST INT, -- HACE REFERENCIA AL ID DEL POST QUE SE COMENTA
    FOREIGN KEY (ID_COMENTARIO_POST) REFERENCES POST_USUARIO(ID_POST),
    ID_COMENTARIO_USUARIO INT, -- HACE REFERENCIA AL ID DEL USUARIO QUE COMENTA EN EL POST
    FOREIGN KEY (ID_COMENTARIO_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    TEXTO_COMENTARIO VARCHAR(300) -- EL TEXTO DEL COMENTARIO
);